### ISSUE TITLE
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

### ISSUE THREAD

**Issue by Mehdizh** [rpj/rpi#20]
Hello,
I am a new to these types of systems and following the guild I managed to get my system up and running and data feeding into Thingspeak, Channel ID: 802605

Issue is the code is failing to a bad internet connection I have, as I run your system through a VPN.
Thought I set up the device in tehran for a laugh as I am on Holiday here.

Are you able to just keep requesting the URL in a constant loop until it connects again?

More code here:
Success: entry #792 added
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/rpi/env/local/lib/python2.7/site-packages/rpjios/SubscriberBase.py", line 54, in _sub_thread
    map(lambda sf: sf(m), self._subs)
  File "/home/pi/rpi/env/local/lib/python2.7/site-packages/rpjios/SubscriberBase.py", line 54, in <lambda>
    map(lambda sf: sf(m), self._subs)
  File "./bin/thingspeak", line 39, in msg_rx
    _resp = urllib2.urlopen(_url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

^CTraceback (most recent call last):
  File "./bin/thingspeak", line 57, in <module>
    time.sleep(0.5)
KeyboardInterrupt

Plus great job on the code even for a total nobe I got it working.

Cheers.
Mehdi

**Comment by Mehdizh** [comment]
Seems to work better now, I reduced the sensor Frequency from 0.5Hz to 0.1Hz, so maybe to much data requests where being sent with a bad internet causing the issues,,,

**Comment by ti-tipakorn** [comment]
I have the same problem, will try to reduced the sensor Frequency

**Comment by ti-tipakorn** [comment]
just change from my DNS to google Public DNS (8.8.8.8)/ Cloudflare DNS (1.1.1.1) and that problem was gone.
