### ISSUE TITLE
REDIS_URL should be a CL arg for sensors-src (or something)

### ISSUE THREAD

**Issue by rpj** [rpj/rpi#7]
`REDIS_URL` handling needs to be fixed, is really the point.

**Comment by mheirendt** [comment]
I've configured redis in the config.json file as follows:
`
{
    redis_config: {
        host: 'host',
        port: port,
        db: 0
    }
}
`

And am seeing the following stack trace:

`
Traceback (most recent call last):
  File "./sensors-src", line 45, in <module>
    ns = sens.create(s['name'], config=s['config'] if 'config' in s else None, redis_cfg=redis_cfg)
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/Sensors.py", line 29, in create
    return cf(**config) if config else cf()
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/SensorBase.py", line 17, in wrapper
    func(*args, **kwargs)
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/SensorBase.py", line 26, in wrapper
    func(*args, **kwargs)
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/sensors/SEN12642.py", line 9, in __init__
    super(Factory, self).__init__(*args, **kwargs)
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/AnalogBase.py", line 10, in __init__
    super(Analog, self).__init__(*args, **kwargs)
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/SensorBase.py", line 59, in __init__
    self._sub = Subscriber(channel=self.channel)
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/SubscriberBase.py", line 17, in __init__
    super(Subscriber, self).__init__(*args, **kwargs)
  File "/usr/projects/rpi/env/local/lib/python2.7/site-packages/rpjios/RedisBase.py", line 13, in __init__
    self._r = redis.StrictRedis(**kwargs)
TypeError: type object argument after ** must be a mapping, not NoneType
Exception AttributeError: "'Subscriber' object has no attribute '_psunsubfunc'" in <bound method Subscriber.__del__ of <rpjios.SubscriberBase.Subscriber object at 0xb6519bd0>> ignored
`
